### ISSUE TITLE
mi sembra che l'immagine sia piazzata stranamente

### ISSUE THREAD

**Issue by marte-git** [anonimo345423/Lweb-Esercizio1#1]
la locandina dei film si sovrappone al testo ... potrebbe dipendere da misure assolute invece che relative

**Comment by anonimo345423** [comment]
Ho fatto il push della correzione, se ora le sembra corretto mi lasci un commento e chiudo l'issue!

**Comment by marte-git** [comment]
mh ... diciamo che rimpicciolendo le immagini si evita la sovrapposizione ...

**Comment by marte-git** [comment]
chiudiamo pure ...

**Comment by anonimo345423** [comment]
Aspetto che lo veda Florin che magari insieme riusciamo a tenere le immagini più grandi senza sovrapposizioni, altrimenti chiudiamo, grazie!
